name: Run All Review Rotations

on:
  schedule:
    # TESTING: Runs at 21:42 Finland Time (18:42 UTC) on October 24, 2025
    - cron: '42 18 24 10 *'
  workflow_dispatch:
    inputs:
      manual_run:
        description: 'Manual run (updates existing column instead of creating new)'
        required: false
        type: boolean
        default: true

jobs:
  all-review-rotations:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: poetry install
      
      - name: Create credentials file
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > credentials.json
      
      - name: Run All Rotations (All Sheets, All Types)
        env:
          CREDENTIAL_FILE: credentials.json
          SHEET_NAMES: ${{ vars.SHEET_NAMES }}
        run: |
          MANUAL_FLAG=""
          
          if [ "${{ github.event.inputs.manual_run }}" = "true" ]; then
            MANUAL_FLAG="--manual"
            echo "🔧 Manual run mode: Will update existing columns"
          else
            echo "📅 Scheduled run mode: Will create new columns"
          fi
          
          # Check if SHEET_NAMES is configured
          if [ -z "$SHEET_NAMES" ]; then
            echo "❌ Error: SHEET_NAMES variable is not configured!"
            echo "   Please set up Variables in Settings → Secrets and variables → Actions → Variables"
            exit 1
          fi
          
          # Display configuration (for debugging)
          echo "📋 Processing sheets:"
          echo "$SHEET_NAMES" | while read -r line; do
            [ -n "$line" ] && echo "   - $line"
          done
          
          echo ""
          echo "🚀 Running rotations for:"
          echo "   - Individual Developers (all sheets)"
          echo "   - Teams (all sheets)"
          echo ""
          
          # Run the multi-sheet rotation (processes ALL sheets, ALL types)
          poetry run python scripts/run_multi_sheet_rotation.py --type all $MANUAL_FLAG
      
      - name: Clean up credentials
        if: always()
        run: rm -f credentials.json
      
      - name: Report Status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ All rotations completed successfully!"
          else
            echo "❌ Some rotations failed - check logs above"
            exit 1
          fi
