name: Multi-Sheet Review Rotation

on:
  schedule:
    # Runs every Wednesday at 5:00 AM Finland Time (3:00 AM UTC)
    - cron: '0 3 * * 3'
  workflow_dispatch:
    inputs:
      rotation_type:
        description: 'Type of rotation to run'
        required: true
        type: choice
        options:
          - all
          - devs
          - teams
        default: 'all'
      manual_run:
        description: 'Manual run (updates existing column instead of creating new)'
        required: false
        type: boolean
        default: false

jobs:
  multi-sheet-rotation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: poetry install
      
      - name: Create credentials file
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > credentials.json
      
      - name: Run Multi-Sheet Rotation
        env:
          CREDENTIAL_FILE: credentials.json
          # Use Variables (not Secrets) for non-sensitive config
          SHEET_NAMES: ${{ vars.SHEET_NAMES }}
          # Fallback to single sheet if SHEET_NAMES not set
          SHEET_NAME: ${{ vars.SHEET_NAME }}
        run: |
          # Determine rotation type and manual flag
          ROTATION_TYPE="${{ github.event.inputs.rotation_type || 'all' }}"
          MANUAL_FLAG=""
          
          if [ "${{ github.event.inputs.manual_run }}" = "true" ]; then
            MANUAL_FLAG="--manual"
          fi
          
          # Check if SHEET_NAMES is configured
          if [ -z "$SHEET_NAMES" ] && [ -z "$SHEET_NAME" ]; then
            echo "❌ Error: Neither SHEET_NAMES nor SHEET_NAME variable is configured!"
            echo "   Please set up Variables in Settings → Secrets and variables → Actions → Variables"
            exit 1
          fi
          
          # Display configuration (for debugging)
          if [ -n "$SHEET_NAMES" ]; then
            echo "📋 Processing multiple sheets:"
            echo "$SHEET_NAMES" | while read -r line; do
              [ -n "$line" ] && echo "   - $line"
            done
          else
            echo "📋 Processing single sheet: $SHEET_NAME"
          fi
          
          # Run the rotation
          poetry run python scripts/run_multi_sheet_rotation.py --type "$ROTATION_TYPE" $MANUAL_FLAG
      
      - name: Clean up credentials
        if: always()
        run: rm -f credentials.json
      
      - name: Report Status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Multi-sheet rotation completed successfully!"
          else
            echo "❌ Multi-sheet rotation failed!"
            exit 1
          fi

